name: Conda build

on:
  workflow_dispatch:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**.py'
      - '**.c'
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
#        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.8, 3.9]
    name: OS ${{ matrix.os }} Python ${{ matrix.python-version }} 
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Create conda environment
        run: |
          conda create -n alm --yes -c conda-forge python=${{ matrix.python-version }}
          conda activate alm
#       - name: Setup conda
#         uses: conda-incubator/setup-miniconda@v2
#         with:
#           activate-environment: alm
#           python-version: ${{ matrix.python-version }}
#           auto-update-conda: true
#           channels: conda-forge
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Install conda libraries
        run: conda install --yes numpy scipy h5py compilers spglib boost eigen cmake
      - run: echo ${CC} ${CXX}
      - name: Build ALM library
        working-directory: ./python
        run: python setup.py build
      - name: Place ALM library
        working-directory: ./python
        run: pip install -e .
      - name: Run test Si
        working-directory: ./test
        run: python Si_fitting.py
      - name: Run test SiC
        working-directory: ./test
        run: python SiC_fitting.py

