name: Build and test ALM using Conda

on: 
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [2.7, 3.7, 3.8, 3.9]
    name: OS ${{ matrix.os }} Python ${{ matrix.python-version }} 
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge
      - run: conda --version
      - name: Install conda libraries
        run: conda install --yes numpy scipy h5py compilers spglib boost eigen cmake
      - name: Build ALM library
        working-directory: ./python
        run: python setup.py build
      - name: Place ALM library
        working-directory: ./python
        run: pip install -e .
      - name: Run test Si
        working-directory: ./test
        run: python Si_fitting.py
      - name: Run test SiC
        working-directory: ./test
        run: python SiC_fitting.py

